/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appliLocation;

import java.sql.Date;

/**
 *
 * @author ESDRAS code integer GENERATED BY DEFAULT AS IDENTITY 
(START WITH 1) PRIMARY KEY, codeLocataire integer, amount int, datePaiement date, 
dateDebut date, dateFin date, motif varchar(50)
 */
public class Facture extends FactureClientInfos {
    private Integer code;
    private String nomLocataire, prenomLocataire;
    public Facture(int code, String nomLocataire, String prenomLocataire, int amount, Date datePaiement, Date dateDebut, Date dateFin, String motif) {
        super(amount, datePaiement, dateDebut, dateFin, motif);
        this.code = code;
        this.nomLocataire = nomLocataire;
        this.prenomLocataire = prenomLocataire;
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getNomLocataire() {
        return nomLocataire;
    }

    public void setNomLocataire(String nomLocataire) {
        this.nomLocataire = nomLocataire;
    }

    public String getPrenomLocataire() {
        return prenomLocataire;
    }

    public void setPrenomLocataire(String prenomLocataire) {
        this.prenomLocataire = prenomLocataire;
    }
}
